# Unique name for this workflow
name: PR Validation
# Definition when the workflow should run
on:
  pull_request:
    types: [edited, opened, synchronize, reopened, review_requested]
    paths:
      - 'force-app/**'
      - 'pmd/**'
      - '.github/workflows/pr.yml'
  workflow_dispatch:
# Jobs to be executed
jobs:
  scratch-org-apex-tests:
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'dependabot[bot]' }}
    steps:
      # Checkout the source code
      - name: 'Checkout source code'
        uses: actions/checkout@v4

      # Install Salesforce CLI
      - name: 'Install Salesforce sf CLI'
        run: |
          npm install @salesforce/cli --global
          sf --version

      # Log out of all orgs to avoid refresh token error
      - name: 'Log out of all orgs'
        run: sf org logout --target-org devhub

      # Store secret for dev hub
      - name: 'Populate auth file with DEVHUB_SFDX_URL secret'
        shell: bash
        run: |
          echo ${{ secrets.DEVHUB_SFDX_URL}} > ./DEVHUB_SFDX_URL.txt
          secretFileSize=$(wc -c "./DEVHUB_SFDX_URL.txt" | awk '{print $1}')
          if [ $secretFileSize == 1 ]; then
              echo "Missing DEVHUB_SFDX_URL secret. Is this workflow running on a fork?";
              exit 1;
          fi
      # Authenticate dev hub
      - name: 'Authenticate Dev Hub'
        run: sf org login sfdx-url --sfdx-url-file ./DEVHUB_SFDX_URL.txt --alias devhub --set-default-dev-hub

      # Add namespace to project config
      - name: Add namespace to project config
        run: |
          sed -i 's,"namespace": "","namespace": "",' sfdx-project.json

      # Create scratch org
      - name: 'Create scratch org'
        run: sf org create scratch --definition-file config/project-scratch-def.json --alias ChatterBINGO --set-default --no-ancestors --duration-days 1 --wait 20 --target-dev-hub devhub

      # Deploy source to scratch org
      - name: 'Push source to scratch org'
        run: sf project deploy start

      # Run Apex tests in scratch org
      - name: 'Run Apex tests'
        run: sf apex run test --code-coverage --detailed-coverage --result-format human --wait 20 --test-level RunLocalTests --output-dir ./

      # Upload code coverage to Codecov.io
      - name: 'Upload code coverage for Apex to Codecov.io'
        uses: codecov/codecov-action@v4
        with:
          flags: Apex
          token: ${{ secrets.CODECOV_TOKEN }}

      # Housekeeping
      - name: 'Delete scratch org'
        if: always()
        run: sf org delete scratch --no-prompt --target-org ChatterBINGO

      # Remove namespace from project config
      - name: Remove namespace from project config
        run: |
          sed -i 's,"namespace": "","namespace": "",' sfdx-project.json

  scan-pmd-action:
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'dependabot[bot]' }}
    steps:
      # Checkout the source code
      - name: 'Checkout source code'
        uses: actions/checkout@v4

      - name: 'Setup java'
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'
      # Run PMD scan
      - name: 'Perform PMD scan with PMD action'
        uses: pmd/pmd-github-action@v2
        id: pmd-action
        with:
          version: 'latest'
          sourcePath: 'force-app'
          rulesets: 'pmd/ruleset.xml'
          analyzeModifiedFilesOnly: false
          createGitHubAnnotations: true
      # Check for PMD violations
      - name: 'Check for PMD violations'
        if: steps.pmd-action.outputs.violations != 0
        run: exit 1
